pinojs/pino-pretty

index.js
test/error-objects.test.js

Fixed `null stack` problem mentioned here: https://github.com/pinojs/pino-pretty/issues/1#issuecomment-378165197

fix: null stack error

---

Readme.md
index.js
package.json
test/basic.test.js

@jsumners @davidmarkclements let me know

Alternative implementation of the meta wrapper

---

Readme.md
bin.js
index.js
package.json
test/basic.test.js
test/cli.test.js

Fixes #6.
It might require #9 and https://github.com/pinojs/pino/issues/395 to work.

Added jmespath

---

index.js
test/basic.test.js

I've found this coming from https://github.com/pinojs/hapi-pino/issues/61.

Do not crash with a property that has value undefined

---

Readme.md

doc: fix v2.x cli options

---

index.js
test/basic.test.js

Pring msg as an object if it is an object.

---

index.js
test/error-objects.test.js

Fixes https://github.com/pinojs/pino-pretty/issues/40

fix: don't crash on undefined errorLikeObject

---

lib/utils.js
test/cli.test.js
test/lib/utils.public.test.js

Added some tests for `prettifyErrorLog` and `prettifyObject`.
Checks functionalities of the specified functions and restores code coverage.

Added tests

---

index.js
test/error-objects.test.js

Properly ignore level; dont show `;` if nothing preceeds it

---

lib/utils.js
test/lib/utils.public.test.js

Log caller when other properties are not present

---

Readme.md

Changed from m to a, following bin.js

Fix short argument key for timestampKey

---

.taprc
bin.js
index.js
lib/colors.js
lib/utils.js
package.json
test/cli-rc.test.js
test/cli.test.js
test/lib/utils.public.test.js

This also update all dependencies  and fixes a few error discovered while bringing the code coverage to 100%.

100% code coverage

---

Readme.md
docs/help.md

PR in refence to https://github.com/pinojs/pino-pretty/issues/105

Systemd example

---

lib/constants.js
test/basic.test.js
test/cli-rc.test.js
test/cli.test.js
test/crlf.test.js

Fixes https://github.com/pinojs/pino-pretty/issues/127

Remove "v" prop from LOGGER_KEYS constant

---

.github/workflows/ci.yml
lib/colors.js
lib/utils.js
package.json
test/basic.test.js
test/error-objects.test.js

Sorry @jsumners, looking through the code trying to figure out why i'm suddenly having issues with `pino-pretty` on Windows, so there may be a few more commits as I go!

chore: add parallel coverage generation; linting

---

index.d.ts
index.js
package.json
test/types/pino-pretty.test-d.ts
tsconfig.json

Part of effort to do https://github.com/pinojs/pino/pull/913

Add TypeScript types

---

index.d.ts
package.json
test/types/pino-pretty.test-d.ts

Export PrettyOptions in ES6-import-friendly way

---

.taprc
package.json
test/basic.test.js
test/cli-rc.test.js
test/cli.test.js
test/crlf.test.js
test/error-objects.test.js
test/lib/colors.test.js
test/lib/utils.internals.test.js
test/lib/utils.public.test.js

updated to tap@15

---

package.json

This is not a production dependency.

Moved @typesb/node to devDependencies

---

bin.js
test/cli-rc.test.js
test/cli.test.js

Fixes #212
---
I'm not sure if the tests could be improved.

Fix shortcut usage of '-a' and '-m' options

---

package.json

fix #237
ref https://github.com/jorgebucaran/colorette/issues/73

Fix broken CJS support

---

Readme.md

Mention the prettyPrint deprecation in the README.

---

lib/utils.js
test/basic.test.js

only output space after key in object if value does not start with eol

---

Readme.md

There are just some minor fixes in readme.md

Fixed markdown in README.md

---

Readme.md

Fix stream examples in README

---

index.d.ts
test/types/pino-pretty.test-d.ts

Adding types for #297 
cc @mcollina  :)

Add type definition for the 'sync' option

---

test/types/pino-pretty.test-d.ts

This should have been included with PR #308

Add missing type test for #300

---

index.d.ts
test/types/pino-pretty.test-d.ts

Fixes type declarations to allow for no options, closes #326

---

lib/utils.js
package.json
test/lib/utils.internals.test.js
test/lib/utils.public.test.js

Fix cloning errors

---

.github/workflows/ci.yml
test/basic.test.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Remove the usage of pino prettyPrint option

---

index.d.ts
test/types/pino-pretty.test-d.ts

add minimumLevel to typings

---

Readme.md

fix messageFormat template from `request.url` to `req.url`

[Doc] fix messageFormat

---

package.json
test/cli-rc.test.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Bumped pino-abstract-transport v1.0.0

---

index.d.ts
test/types/pino-pretty.test-d.ts

Align export in index.d.ts and index.js

---

Readme.md

Also updated example text, as color and time args weren't used when running the script to generate the new example image.

docs(readme): update example link

---

Readme.md
bin.js
help/help.txt
index.d.ts
index.js
lib/utils.js
test/basic.test.js
test/lib/utils.public.test.js

Closes #363.
* The new option is named `include`.
* `--ignore` will be ignored if `--include` is passed in.
* CLI long flag is `--include` and short flag `--I`.

A new option for users to choose log keys to include

---

lib/utils/index.js
lib/utils/index.test.js

Manually require and export all util scripts

---

Readme.md

fix: ndjson incorrect url

---

.github/workflows/ci.yml

chore: enable node 24 in CI

---

lib/colors.test.js

This PR moves colors.test.js to node test

test: move colors.test.js to node test

---

lib/utils/prettify-time.test.js

This PR moves `prettify-time.test.js` to node test

test: move prettify-time.test.js to node test

---

package.json
test/basic.test.js

This PR moves `basic.test.js` to node test

test: move basic.test.js to node test

---

test/crlf.test.js

This PR moves `crlf.test.js` to node test

test: move crlf.test.js to node test

---

lib/utils/prettify-error.test.js

This PR moves `prettify-error.test.js` to node test

test: move prettify-error.test.js to node test

---

eslint.config.js
package.json

Use neostandard and remove pre-commit
