pinojs/pino-pretty

Readme.md, bin.js, index.js, test/basic.test.js
remove `--dateFormat` and `--localTime` options
`--translateTime` (`-t`) accept an optional format string
- `-t` convert into UTC ISO format, default: `yyyy-mm-dd HH:MM:ss.l o`
- `-t 'HH:MM:ss.l'` convert into UTC in 'HH:MM:ss.l' format
- `-t 'SYS:standard'` convert into system's timezone, default: `yyyy-mm-dd HH:MM:ss.l o`
- `-t 'SYS:HH:MM:ss'` convert into system's timezone in 'HH:MM:ss' format
=> translateTime accept an optional format string

Readme.md, index.js, package.json, test/basic.test.js
=> Removes the `.asMetaWrapper` method since it is in core

Readme.md
emphasises using `pino-pretty` as a CLI tool and shows how to integrate with Pino programatically without `asMetaWrapper`.
=> next-major: clarify the readme

index.js, test/error-objects.test.js
=> do not treat errors without a stack as errors

index.js, test/basic.test.js
check if value is undefined after calling JSON.stringify(value).
If the value is undefined the output is skipped preserving indentation.
Added a test verifying both error and non error like keys that resolve to undefined.
Undefined values can occur in a number of scenarios, some being -
* The value is a function `JSON.stringify(f => f)` => undefined
* The value is a class `JSON.stringify(class F {})` => undefined
* The value is a symbol `JSON.stringify(Symbol.for('x'))` => undefined
* The value has a serialize function that returns undefined `JSON.stringify({ toJSON() {} })` => undefined
=> skip undefined values, fixes #45

index.js, test/basic.test.js
This PR checks for a `time` on the log object and either operates as normal or totally ignores that section of the log if `time` falsey.
One thing to note - getting the spaces between the timestamp and the level strings was tricky, that's why I needed to do this:
```js
const lineOrEmpty = line && line + ' '
line = `${lineOrEmpty}${coloredLevel}`
```
Otherwise it would output this (notice the leading space):
```
LEVEL ...
LEVEL ...
```
Happy to make any necessary changes, just let me know 😊 
Closes #48
=> Omit empty brackets if log.time is falsey

index.js, package.json, test/basic.test.js
This PR uses the same [fast-safe-stringify](https://github.com/davidmarkclements/fast-safe-stringify) library used in [pino](https://github.com/pinojs/pino) to avoid errors about circular references when logging.
Example:
```js
'use strict';
const pino = require('pino');
const logger = pino({
prettyPrint: {
levelFirst: true
},
prettifier: require('pino-pretty')
});
const logInfo = { a: 1, b: 2 };
// Circular reference
logInfo.c = logInfo;
// This could throw an error due to the circular reference
logger.info(logInfo, 'an info log');
```
This PR closes #51.
=> Add safe stringify

Readme.md, bin.js, index.js, test/basic.test.js, test/cli.test.js
I love `pino` and `pino-pretty` but I really don't care about the pid and hostname on my dev machine. I added a new option `--ignore` to customize the output.
Example use:
```sh
$ echo '{"level":30,"time":1522431328992,"msg":"hello world","pid":42,"hostname":"foo","v":1, "name":"pou"}' | node bin.js -ti pid,hostname,name
[2018-03-30 17:35:28.992 +0000] INFO : hello world
```
Note: I added a few tests
=> New option and command line argument to ignore some keys

index.js, package.json, test/lib/utils.internals.test.js
See #63 for details. And I'm updated tests for GMT+7 or upper timezones. In these timezones test string `2019-04-06T13:30:00.000-04:00` is `7 Apr 2019 00:30`.
=> [dependencies] bourne updated

Readme.md, bin.js, index.js, lib/constants.js, lib/utils.js, test/lib/utils.public.test.js
=> Support custom timestamp property

index.js, test/basic.test.js
Checks for number input and prevents crashing as reported in issue #69
Example: `node -e 'console.log(2)' | node ./bin.js`
=> add check for numbers

lib/utils.js, test/lib/utils.public.test.js
When trying to format a log object like the following:
```json
{
"level": 30,
"time": 0,
"name": "foobar",
"msg": "I like cake",
"v": 1
}
```
pino-pretty previously tried to format the timestamp `undefined` instead of
taking the `0` time. This commit looks not at the truthiness of the value, but
its existence.
=> Handle timestamp 0 in prettifyTime

index.js, test/cli.test.js
* Add test for passing through double-quoted string from JSON.stringify(new Date())
* Check for parsed value being JS object, otherwise just fallthrough as on parse error
=> Pass through non-object valid JSON, fixes #72

Readme.md, index.js, lib/utils.js, test/basic.test.js
The reasoning behind this is that `pino-pretty` can be extended to cover  some uses cases of log outputs that provide additional keywords. Main example would be `sequelize` which log provides the `query` property on the log output. Using `customPrettifiers` option that content of `query` prop can be prettified and formatted. 
This would eliminate the need for writing a custom prettifier for `pino` for these simple cases.
=> feat: support custom key prettifiers as option

Readme.md, bin.js, index.js, lib/utils.js, test/lib/utils.public.test.js
Add `messageFormat` for combining some useful log properties into `msg`. And combined properties can be ignored.
Since `pino-pretty` is recommended for development only,  may `messageFormat` is a flexible way for module, for example:
```js
// log
{
module: 'repository',
msg: 'foo'
}
// options
{
messageFormat: '[{module}] - {msg}',
ignore: 'module',
}
```
The result will be `[repository] - foo`.
=> feat: add messageFormat option for msg

lib/constants.js, lib/utils.js, test/basic.test.js
If the `caller` property exists (like from [pino-caller](https://github.com/pinojs/pino-caller)), include it in the info line.
=> Prettify `caller` property

Readme.md, bin.js, index.js, lib/constants.js, lib/utils.js, test/basic.test.js
This would resolve https://github.com/pinojs/pino-pretty/issues/91
I've named the option `changeLevelName` to be in line with the option in pino.
I wasn't too sure about the short form for `--changeLevelName`, since both `-c` and `-l` were already used, so right now there is no short form.
=> Add --changeLevelName option

Readme.md
This PR updates readme badges. For convenience reasons I included npm package version badge and also switched existing ones to https://badgen.net using it as universal badge provider.
=> Update readme badges

index.js, test/basic.test.js, test/cli.test.js
This allows the prettifiedTime function run before any of the properties are filtered from the log object. If you are using a timestampKey that is also ignored it will still work.
Issue described in: https://github.com/pinojs/pino-pretty/issues/116
=> Prettify Time Before Filtering

bin.js, test/cli-rc.test.js
I encountered some unexpected behavior where `errorProps` and `errorLikeObjectKeys` cannot be set from a config file. I found this had previously been reported in #94.
In this pull request, I have added a test to ensure that `errorProps` can override the defaults via a config file. I changed when the default values for these mentioned options are applied to address the issue. Instead of being applied at command-line options parsing time, these defaults are applied after the config is dealt with.
=> allow "errorProps" and "errorLikeObjectKeys" to be set by config file

index.js, test/basic.test.js, test/cli.test.js
This reverts commit 38beec137545b9fb7564f5f5f5d3c8a27fcbb9bd.
@BenGale unfortunately #117 broke pino-multi-stream and other (see https://github.com/pinojs/pino-multi-stream/pull/38)
The problem of the change in #117 is that it disables the ability to remove the timestamp from the main log line. I guess you'll have to file a different issue to solve your problem.
I've also added a regression test.
=> Revert "Prettify Time Before Filtering (#117)"

index.js, test/basic.test.js, test/cli.test.js
@mcollina This is related to: https://github.com/pinojs/pino-pretty/pull/119
I took another look at a better way for this to be handled and it seems like there is already something handling overrides for the messageKey and the levelKey, so I have extended that to also support timestampKey. Apologies for not spotting this on the first fix PR.
There are tests to cover this and make sure it isn't outputted in the prettified object.
=> Skip timestampKey in Prettified Object

index.js, test/basic.test.js
Here is my fix for issue #129. There were two spots in pretty() where it was adding a space, even if the line to that point was empty, so I added tests for and fixed both.
=> Avoid adding spaces at the beginning of the line, fixes #129

Readme.md
=> (docs) fix example

Readme.md, bin.js, index.js, test/basic.test.js
This PR adds the flag 'hideObject' that allows users to choose disabling the print of objects on logs (i.e `prettifyObject()` call). I tried to modify the least code as possible to meet this goal.
=> feature: Add a flag to hide object from output (--hideObject)

Readme.md, bin.js, index.js, lib/utils.js, test/basic.test.js, test/cli.test.js, test/error-objects.test.js, test/lib/utils.internals.test.js
This adds a `singleLine` config option. When enabled, all unrecognized non-error fields will be printed on the same line as the main log message, as a simple JSON string. Error messages are still printed like normal, on a new line.
The implementation for this is **very** rough. I wanted to get feedback on the design/behavior before I spent any time polishing the code. I also haven't updated any docs yet. The tests should provide all the examples/behavior definitions needed though.
This builds off of #125 and hopefully fixes #97.
Remaining work:
=> Add `singleLine` config option

index.js, test/basic.test.js
A bug in #158 left a trailing space on lines that had no extra log fields with singleLine=true. This commit fixes that, and updates a test accordingly.
I'm sorry I didn't notice this in my initial PR, considering I wrote a test that included the bug.
=> Fix trailing space in singleLine mode

lib/utils.js, test/lib/utils.public.test.js
I updated from 4.7.1 to 5.0.1 and I kept getting an error regarding `rfdc`. Eventually tracked it down to this library. It seems like it was introduced in https://github.com/pinojs/pino-pretty/pull/180
```
/home/blaenk/code/app/bot/node_modules/rfdc/index.js:39
if (o instanceof Date) return new Date(o)
^
RangeError: Maximum call stack size exceeded
at Function.[Symbol.hasInstance] (<anonymous>)
at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:39:11)
at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:58:17)
at cloneArray (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:31:17)
at clone (/home/blaenk/code/app/bot/node_modules/rfdc/index.js:40:34)
at cloneArray …
```
=> Fix broken circular reference handling when filtering

test/cli-rc.test.js
Cloned a fork, installed dependencies and ran tests on master as a 1st step to work on a PR.
However, alas - it failed tests out of the box because the tests assume a `\n` line ending where the windows host I was working on uses `\r\n`.
=> Make tests platform independent

lib/utils.js, test/lib/utils.internals.test.js, test/lib/utils.public.test.js
Fixes #198
* When the `time` value cannot be parsed to a Date, leave it unformatted
* Allow epoch as the `time` value to be a number or string
Example:
```sh
(
echo '{"time":"1623170292956","msg":"one"}'
echo '{"time":1623170292956,"msg":"two"}'
echo '{"time":"2 days ago","msg":"three"}'
) | npx pino-pretty --translateTime
```
Old behaviour: 
```
```
(emits nothing)
New behaviour:
```
[2021-06-08 16:38:12.956 +0000]: one
[2021-06-08 16:38:12.956 +0000]: two
[2 days ago]: three
```
=> Permit non-standard time with --translateTime set

index.d.ts, test/types/pino-pretty.test-d.ts
Hello,
This PR adds `customPrettifiers` to type declarations because it was missing. Description and example were taken from the original documentation ([ref](https://github.com/pinojs/pino-pretty#options)).
=> Added type declaration for custom prettifiers

Readme.md, lib/utils.js, test/cli.test.js, test/lib/utils.internals.test.js, test/lib/utils.public.test.js
This PR fixes the issue reported by @acidoxee in https://github.com/pinojs/pino-pretty/issues/132#issuecomment-861608098 just before the issue was closed. 
This commit attempts to overcome the limitation by allowing the user to escape the dot character used as a delimiter.
The method used is to split the key by the dot delimiter ignoring any escaped dots, followed by replacing all occurrences of the escaped dots. Alternatively, it is possible to use a negative lookbehind regex for the split, but might not be supported on all browsers.
Thanks!
=> Fix 'ignore' for keys containing key delimiter

.github/workflows/ci.yml, .taprc, Readme.md, index.js, lib/colors.js, lib/utils.js, package.json, test/cli.test.js, test/example/example.js
=> Switch from chalk to colorette

bin.js, index.js, package.json, test/basic.test.js, test/cli.test.js, test/crlf.test.js, test/error-objects.test.js
This change makes this module compatible with the new transport system.
This is the first step for https://github.com/pinojs/pino/issues/1106.
It is a semver-major change and it will require a minor change in pino@6 and pino@7 to achieve compatibility. before we exported the `prettyFactory`, now we export the function to build a transport, which includes split2.
=> Use pino-abstract-transport

Readme.md, index.d.ts, index.js, package.json, test/basic.test.js, test/cli.test.js, test/types/pino-pretty.test-d.ts
Fixes https://github.com/pinojs/pino-pretty/issues/223
=> Removed jmespath

Readme.md, index.js, lib/colors.js, package.json
=> Update colorette to enable behaviour consistent with earlier pino-pretty versions

.github/workflows/ci.yml, package.json
As `dateformat` moved from `CJS` to `ESM`.
Change the version to `~` flag to prevent further impact.
Related to https://github.com/pinojs/pino/pull/1137
=> fix: dateformat migrated to esm

Readme.md, bin.js, index.js, test/basic.test.js
Fixes #100 
There were a few leftover lines in `bin.js` for the old `search` flag (removed in #227), so I reused that example in this PR. (I also re-used the implementation and testing strategies from that old feature to implement this one.)
I just wanted to get this feature as close to shippable as possible, please feel free to close this PR and re-implement a different way if this isn't the right approach. 👍
=> Add support for minimumLevel

Readme.md, index.js, test/basic.test.js
Adds a couple of missing options
=> Support SonicBoom as a destination

Readme.md, index.js, lib/utils.js, test/basic.test.js, test/lib/colors.test.js
This would close issues like #185, and put more formatting capabilities into userland.
If another option-key besides `customPrettifiers` should be used I'm happy to switch. I think the docs are a bit open to interpretation even though I see this option is only being used to prettify object-formatting right now.
=> Add ability to format time and level with user-defined prettifiers

Readme.md
Hello!
As stated in the title, this add an example on how to use pino-pretty as stream while still passing pino options.
=> chore: Added example to provide pino core options.

index.js, test/error-objects.test.js
Here's how the output currently looks:
```
[1637396183072] ERROR: something bad happened    Error: something bad happened
at Object.<anonymous> (/tmp/pino-lab/fiddle.js:16:9)
```
Here's what we expect:
```
[1637396183072] ERROR: something bad happened
Error: something bad happened
at Object.<anonymous> (/tmp/pino-lab/fiddle.js:16:9)
```
=> append missing eol before appending prettified error object when singleLine=true

index.js, test/basic.test.js
=> allow sonic-boom to filter call to close on stdout

bin.js, package.json, test/cli-rc.test.js
If your project is ESM by default, then you need to make common js files have the cjs extension to load. This just adds that to the list of files to try loading.
I have also removed the custom joycon loader, because it always tries to parse JSON now.
=> Allow loading common js config files by default

Readme.md, index.js, lib/utils.js, test/basic.test.js
So folks can prettify the pid, logger name, or hostname as they see fit!
=> Add support for custom prettifiers on the metadata

Readme.md, index.d.ts, test/types/pino-pretty.test-d.ts
=> Add missing TypeScript declarations (#300)

Readme.md
As discussed in https://github.com/pinojs/pino-pretty/issues/305
=> doc: Shell limitation

.taprc, index.js, lib/utils.js, package.json, test/lib/utils.public.test.js
Added the following [block](https://github.com/pinojs/pino/blob/f8696ab5fb0e5a819b6255af420b29fb075cbdee/lib/tools.js#L335-L373) to build safe sonic boom.
Closes #304
=> fix: building sonic boom safe

Readme.md
=> [Doc] Fix typo by replacing 'hostname' with 'pid'

.taprc, Readme.md, index.js, lib/constants.js, lib/utils.js, test/basic.test.js, test/cli-rc.test.js, test/cli.test.js, test/crlf.test.js, test/error-objects.test.js, test/lib/utils.internals.test.js, test/lib/utils.public.test.js
We say that `pino-pretty` is a _development_ tool, however it's very verbose in its default settings to use for local development. In this PR I simplified it a bit:
1. Use the local timezone and just print the time. If I'm developing code I want to reason on my own timezone and I'm not interested in what day it is.
2. remove the hostname as it's unlikely to change given that's my development machine.
This was inspired by https://github.com/fastify/fastify-cli/issues/536
=> Line simplification for development

help/help.txt
Fix the wrong example of the include flag in help.txt.
Thanks to @glensc spotting the issue in a previous [PR](https://github.com/pinojs/pino-pretty/pull/373/files#r958686611).
=> Fix the include flag example in help.txt

index.d.ts, index.js, lib/utils.js, test/lib/utils.public.test.js
Hello, i made the changes to make possible pass in code as object or string the customLevels prop, it's still compatible with the CLI passing as string parameter.  I already wrote the tests too and keeps on the 100% coverage and asserted.
Is relative to #399 .
=> feat: adding possibility to pass an object as parameter to customLevels

lib/utils.js, test/lib/utils.public.test.js
Closes #378 , I'm not pretty sure about the way that I made it, but I think creating a function to do exactly that line of code is unnecessary.
=> feat: dont print escape backslash on strings containing escaped backslashes

Readme.md, bin.js, index.d.ts, index.js, test/basic.test.js
This allows log parsers that can detect JSON at the end of a log line to do so without being thrown off by ANSI colors.
Specifically, we're using Pino + Pino Pretty with Papertrail. Papertrail has [this feature](https://www.papertrail.com/help/json-search/) where they parse JSON at the end of a line. But their JSON parser fails to do so when that JSON is surrounded by ANSI codes.
I could disable colorization altogether, but Papertrail does nicely present ANSI colored logs in their web-UI, so I don't want to do that.
I've sent the Papertrail devs a message, because I think it'd be nicest if it were solved on their side, but as a plan B, and for the time being, this is the next best solution.
=> Add a colorizeObjects option to disable object colorization

Readme.md, lib/utils.js, test/lib/utils.internals.test.js
This PR allows specifying the nested `levelKey`. Such keys will be treated just like the `ignore` nested keys.
There are two reasons for this change:
1. Why would the `ignore` option support nested keys and `levelKey` don't?
2. I personally need it because in my project I use the custom format of logs, where the `level` is placed inside another `tags` object
=> Support nested levelKey

index.js, lib/utils.js, test/basic.test.js
=> fix: adds support for printing number and boolean messageKey value type

index.d.ts, test/types/pino-pretty.test-d.ts
See https://github.com/pinojs/pino-pretty/issues/439
Also contains minor cleanup of type test-file.
---
This assumes `index.d.ts` is managed manually and not autogenerated by some process as I didn't see any related script in `package.json`.
Also I've not worked with [TSD](https://github.com/SamVerschueren/tsd) so far, so I only added the missing example values for `customLevels` and `customColors` parameters to the options. 
A quick inverse check confirmed tests working as expected as they failed without adding `customColors` to the type definition. :+1:
=> Add customColors to typescript definition for PrettyOptions

.github/workflows/ci.yml, .taprc, .taprc.yaml, package.json
We have 100% coverage and tap will error out if we drop below it. We don't need Coveralls's comment spam to tell us coverage dropped.
=> Remove coveralls

Readme.md, lib/utils.js, test/lib/utils.internals.test.js, test/lib/utils.public.test.js
See [#441](https://github.com/pinojs/pino-pretty/issues/441)
---
It's now possible to pass `--messageFormat` option containing conditional statements for log data.
Example log data:
`{level: 30, req: {id: 'foo'}}`
Example `--messageFormat` containing conditional:
`"{level} - {if req.id}({req.id}){end}{if msg} - {msg}{end}"`
Example output:
`"30 - (foo)"`
Unescaped if / end block  within `--messageFormat` will just be deleted.
=> Add support for messageFormat strings containing conditionals

benchmark.js, package.json
As noted in the script, we don't really care about these numbers, but they should help us understand how features affect performance.
On my M1, using 18.17.1, I get:
```
basicLog*10000: 776.762ms
objectLog*10000: 656.023ms
coloredLog*10000: 729.25ms
customPrettifiers*10000: 740.291ms
logWithErrorObject*10000: 564.892ms
logRemappedMsgErrKeys*10000: 580.711ms
messageFormatString*10000: 945.966ms
basicLog*10000: 727.929ms
objectLog*10000: 654.281ms
coloredLog*10000: 736.466ms
customPrettifiers*10000: 724.02ms
logWithErrorObject*10000: 556.315ms
logRemappedMsgErrKeys*10000: 558.546ms
messageFormatString*10000: 918.586ms
```
=> Add basic benchmark suite

index.js, lib/colors.js, lib/pretty.js, lib/utils/filter-log.js, lib/utils/filter-log.test.js, lib/utils/parse-factory-options.js, lib/utils/prettify-error-log.js, lib/utils/prettify-error-log.test.js, lib/utils/prettify-level.js, lib/utils/prettify-level.test.js, lib/utils/prettify-message.js, lib/utils/prettify-message.test.js, lib/utils/prettify-metadata.js, lib/utils/prettify-metadata.test.js, lib/utils/prettify-object.js, lib/utils/prettify-object.test.js, lib/utils/prettify-time.js, lib/utils/prettify-time.test.js, test/error-objects.test.js
This PR refactors all of the prettify functions to use a context object. This removes the need to keep track of all of the parsed options and other items such functions need in order to perform their work. I believe this will make the code base easier to maintain going forward, and will make PRs like #445 easier to implement.
----
It's not clear to me why the following block of code in https://github.com/pinojs/pino-pretty/commit/770f56a44e0d4a30e2809c379ded5647aeba43df stops working when refactoring it to use the context object:
https://github.com/pinojs/pino-pretty/blob/fa386a964cce7d7c5cbeb4ce5bb8d28785001acd/index.js#L117-L122
The short of it is that the following test starts failing:
https://github.com/pinojs/pino-pretty/blob/fa386a964cce7d7c5cbeb4ce5bb8d28785001acd/test/basic.test.js …
=> Refactor functions to use context object

Readme.md, index.js, lib/colors.js, lib/pretty.js, lib/utils/filter-log.js, lib/utils/filter-log.test.js, lib/utils/index.js, lib/utils/interpret-conditionals.js, lib/utils/join-lines-with-indentation.js, lib/utils/parse-factory-options.js, lib/utils/prettify-error-log.js, lib/utils/prettify-error-log.test.js, lib/utils/prettify-error.js, lib/utils/prettify-level.js, lib/utils/prettify-level.test.js, lib/utils/prettify-message.js, lib/utils/prettify-message.test.js, lib/utils/prettify-metadata.js, lib/utils/prettify-metadata.test.js, lib/utils/prettify-object.js, lib/utils/prettify-object.test.js, lib/utils/prettify-time.js, lib/utils/prettify-time.test.js, test/error-objects.test.js
This PR is step 2 of #449. It adds several jsdoc blocks and improves existing ones.
=> Improve jsdoc blocks

Readme.md
Removes the `config` option from the README's programmatic options. The `config` option is only relevant to CLI usage.
A possible related enhancement could be to error for any "unknown" options (for example, passing `config` for programmatic usage is silently ignored at the moment).
Resolves https://github.com/pinojs/pino-pretty/issues/429
=> chore: Remove `config` from README programmatic usage options

LICENSE
Same issue as pinojs/pino#1859
Currently, GitHub cannot detect the license for this project. The note about the pino team in the LICENSE file prevents GitHub from being able to detect the license. The GitHub documentation notes the following:
> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your _LICENSE_ file and note the complexity somewhere else, such as your repository's _README_ file.
In order to keep the whole thing intact and allow the license to be detected, I combined the two lines.
GitHub [uses the ruby gem licensee](https://docs.github.com/en/repositories/managing-your-repositorys-se …
=> chore(license): make detectable by GitHub

help/help.txt
> $ pino pretty
>`pino` cli has been removed. Use `pino-pretty` cli instead.
>
> See: https://github.com/pinojs/pino-pretty
=> Update help.txt: Fix program name

Readme.md, index.d.ts, lib/colors.js, lib/utils/get-level-label-data.js, lib/utils/index.js, lib/utils/parse-factory-options.js, lib/utils/prettify-level.js, lib/utils/prettify-level.test.js, lib/utils/prettify-message.js, lib/utils/prettify-message.test.js, lib/utils/prettify-object.js, lib/utils/prettify-object.test.js, test/basic.test.js, test/types/pino-pretty.test-d.ts
This PR is combined changes from #493 and #494 (see these comments [1](https://github.com/pinojs/pino-pretty/pull/493#issuecomment-1964469268) [2](https://github.com/pinojs/pino-pretty/pull/493#issuecomment-1971957478)). Summary of changes:
All "format" functions -- `customPrettifiers`, `level`, and `messageFormat` -- now have an additional parameter, `extras` that is an object of `Record<string, any>`. This allows for additional data and future (optional) functionality to be provided to these functions without having to change function signature again.
This change is backward compatible but the examples in the documentation for these functions has been updated to include the existing, full, list of parameters that were available instead of just the first parameter. EX
Previous:
```js
{ …
```
=> Providing additional functionality to customPrettifiers and messageFormat

.gitignore, lib/utils/parse-factory-options.js, test/basic.test.js
Documentation notes that options.customColors can be either a string or object but objects are not currently supported in the code.
From index.d.ts:
/**
* Change the level colors to an user custom preset.
*
* Can be a CSV string in 'level_name:color_value' format or an object.
* Also supports 'default' as level_name for fallback color.
*
* @example ( CSV ) customColors: 'info:white,some_level:red'
* @example ( Object ) customColors: { info: 'white', some_level: 'red' }
*/
customColors?: string|object;
This change permits either strings or objects to be used.
=> Support objects in options.customColors

package.json, test/basic.test.js
Closes #477
Problem fixed here https://github.com/planttheidea/fast-copy/issues/94
- **Add test for Object.create(null)**
- **Update fast-copy**
=> Fix Object.create(null)

lib/pretty.js, test/basic.test.js
=> fix: pass error-like objects (#505)

Readme.md, index.d.ts, index.js, test/basic.test.js
- Exporting `isColorSupported` from `Colorette` to check for color support without installing the dependency again.
- Also required in this PR https://github.com/fastify/one-line-logger/pull/42
=> feat: Added exports color support in TTY

lib/utils/prettify-metadata.js, lib/utils/prettify-metadata.test.js
=> fix: add injection of lacking arguments of customPrettifiers

index.d.ts, test/types/pino-pretty.test-d.ts
Hello,
I started using pino-pretty in a TypeScript project and noticed the `useOnlyCustomProps` option is not present in the type definitions module. The JSDoc lists it at [L71-72](https://github.com/pinojs/pino-pretty/blob/77e85fdcf3413b5064c5258ea3b858eac230340f/index.js#L71-L72), so I assume it was a copy-paste error at some time.
This pull request addresses this discrepancy by copying the [readme's description](https://github.com/pinojs/pino-pretty/blob/77e85fdcf3413b5064c5258ea3b858eac230340f/Readme.md?plain=1#L80)!
=> Fix: add missing useOnlyCustomProps options to type definitions

lib/pretty.js, test/basic.test.js
=> fix: unescape \\ for levelKey

.github/workflows/ci.yml, index.js, package.json, test/basic.test.js, test/example/example.js
closes https://github.com/pinojs/pino-pretty/issues/541
=> chore: replace readable-stream with built-in stream

Readme.md
Remove "$" because otherwise, it will also be copied to the clipboard and the pasted command will produce an error.
=> Readme.md: remove the command prompt symbol

Readme.md, bin.js, lib/colors.js, lib/utils/prettify-error-log.test.js, lib/utils/prettify-object.js, lib/utils/prettify-object.test.js
Fixes https://github.com/pinojs/pino-pretty/issues/537 as well.
=> Add magenta as the color for printed object properties. Fixes suport for `--no-colorizeObjects`

bin.js, index.d.ts, index.js, lib/utils/build-safe-sonic-boom.js, lib/utils/build-safe-sonic-boom.test.js, lib/utils/index.test.js, test/basic.test.js, test/cli-rc.test.js, test/cli.test.js, test/crlf.test.js, test/error-objects.test.js, test/example/example.js
Allows redundant `require.cache` calls to be bypassed for builtin modules, saving a few yoctoseconds.
See https://nodejs.org/api/modules.html#core-modules and [discussion in nodejs/node repo regarding why `require.cache` calls are redundant for builtins](https://github.com/nodejs/node/pull/37246/files#r588397158).
Also cleaned up some of the imports by destructuring them whilst I was in the area.
=> perf: use `node:` prefix to bypass require.cache call for builtins

bin.js, test/example/example.js
This PR adds missing `'use strict'` directives to the cjs files in this repo. Strict mode can improve performance by eliminating some JavaScript features that hinder optimizations. It also helps avoid subtle bugs by enforcing more consistent scoping and variable declarations.
The [MDN article on strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) alludes to it, but the V8 JS engine used by Node will use more optimised execution paths when strict mode is enabled. See [related Stack Overflow discussion](https://stackoverflow.com/questions/38411552/why-use-strict-improves-performance-10x-in-this-example) for an example.
=> perf: add missing `'use strict'` directives

.borp.yaml, package.json
This PR adds borp to run tests and  enables the project to move to node test
=> test: enable borp to move to node test

lib/utils/index.test.js
This PR moves `index.test.js` to node test
=> test: move index.test.js to node test

test/error-objects.test.js
This PR moves `error-objects.test.js` to node test
=> test: move error-objects.test.js to node test

lib/utils/build-safe-sonic-boom.test.js
This PR moves `build-safe-sonic-boom.test.js` to node test
=> test: move build-safe-sonic-boom.test.js to node test

lib/utils/filter-log.test.js
This PR moves `filter-log.test.js` to node test
=> test: move filter-log.test.js to node test

lib/utils/format-time.test.js
This PR moves `format-time.test.js` to node test.
=> test: move format-time.test.js to node test

lib/utils/get-property-value.test.js
This PR moves `get-property-value.test.js` to node test
=> test: move get-property-value.test.js to node test

lib/utils/prettify-error-log.test.js
This PR moves `prettify-error-log.test.js` to node test
=> test: move prettify-error-log.test.js to node test

lib/utils/prettify-metadata.test.js
This PR moves `prettify-metadata.test.js` to node test
=> test: move prettify-metadata.test.js to node test

index.d.ts, test/types/pino-pretty.test-d.ts
The fourth parameter of the 'level' custom prettifier -- extras -- used to have a separate type as pino-pretty offered two additional attributes to this particular prettifier.
However since it used a Record<string, T> type, TypeScript required all values to be compatible with each other. So when users tried to use the extras parameter for 'level', it caused
error TS2322: Type '{ level: (_level: string | object, _levelKey: string, _log: object, { labelColorized }: PrettifierExtras<LevelPrettifierExtras>) => string; }' is not assignable to type 'Record<string, Prettifier<object>> & { level?: Prettifier<LevelPrettifierExtras> | undefined; }'.
Type '{ level: (_level: string | object, _levelKey: string, _log: object, { labelColorized }: PrettifierExtras<LevelPrettifierExtras>) => string; }' is …
=> fix: loosen up customPrettifiers typing constraints
